// Code generated by protoc-gen-go. DO NOT EDIT.
// source: info/info.proto

package info

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// A Report about the service
type Report struct {
	// Version of the service
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// Build date of the service
	Date string `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	// Repository name
	Repo                 string   `protobuf:"bytes,3,opt,name=repo,proto3" json:"repo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Report) Reset()         { *m = Report{} }
func (m *Report) String() string { return proto.CompactTextString(m) }
func (*Report) ProtoMessage()    {}
func (*Report) Descriptor() ([]byte, []int) {
	return fileDescriptor_3955287c00436ed0, []int{0}
}

func (m *Report) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report.Unmarshal(m, b)
}
func (m *Report) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report.Marshal(b, m, deterministic)
}
func (m *Report) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report.Merge(m, src)
}
func (m *Report) XXX_Size() int {
	return xxx_messageInfo_Report.Size(m)
}
func (m *Report) XXX_DiscardUnknown() {
	xxx_messageInfo_Report.DiscardUnknown(m)
}

var xxx_messageInfo_Report proto.InternalMessageInfo

func (m *Report) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Report) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *Report) GetRepo() string {
	if m != nil {
		return m.Repo
	}
	return ""
}

// A Health report about the service
type Health struct {
	// Health state
	Alive                bool     `protobuf:"varint,1,opt,name=alive,proto3" json:"alive,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Health) Reset()         { *m = Health{} }
func (m *Health) String() string { return proto.CompactTextString(m) }
func (*Health) ProtoMessage()    {}
func (*Health) Descriptor() ([]byte, []int) {
	return fileDescriptor_3955287c00436ed0, []int{1}
}

func (m *Health) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Health.Unmarshal(m, b)
}
func (m *Health) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Health.Marshal(b, m, deterministic)
}
func (m *Health) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Health.Merge(m, src)
}
func (m *Health) XXX_Size() int {
	return xxx_messageInfo_Health.Size(m)
}
func (m *Health) XXX_DiscardUnknown() {
	xxx_messageInfo_Health.DiscardUnknown(m)
}

var xxx_messageInfo_Health proto.InternalMessageInfo

func (m *Health) GetAlive() bool {
	if m != nil {
		return m.Alive
	}
	return false
}

func init() {
	proto.RegisterType((*Report)(nil), "info.Report")
	proto.RegisterType((*Health)(nil), "info.Health")
}

func init() {
	proto.RegisterFile("info/info.proto", fileDescriptor_3955287c00436ed0)
}

var fileDescriptor_3955287c00436ed0 = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x8f, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0xd9, 0x75, 0xed, 0xee, 0x86, 0x05, 0x25, 0x88, 0x94, 0x2a, 0x22, 0x05, 0xd1, 0x53,
	0x82, 0xfa, 0x04, 0x0a, 0xcb, 0xaa, 0xc7, 0x1e, 0xbd, 0xa5, 0x35, 0x6d, 0x83, 0x6d, 0x26, 0xa4,
	0xb3, 0x05, 0xaf, 0x3e, 0x81, 0xe0, 0xa3, 0xf9, 0x0a, 0x3e, 0x88, 0x64, 0xb2, 0x7b, 0xf6, 0x12,
	0xfe, 0xff, 0xcf, 0xf0, 0xcd, 0x3f, 0xec, 0xc8, 0xd8, 0x1a, 0x64, 0x78, 0x84, 0xf3, 0x80, 0xc0,
	0x67, 0x41, 0x67, 0xe7, 0x0d, 0x40, 0xd3, 0x69, 0xa9, 0x9c, 0x91, 0xca, 0x5a, 0x40, 0x85, 0x06,
	0xec, 0x10, 0x67, 0xb2, 0xb3, 0xdd, 0x2f, 0xb9, 0x72, 0x5b, 0x4b, 0xdd, 0x3b, 0xfc, 0x88, 0x9f,
	0xf9, 0x0b, 0x4b, 0x0a, 0xed, 0xc0, 0x23, 0x4f, 0xd9, 0x7c, 0xd4, 0x7e, 0x30, 0x60, 0xd3, 0xc9,
	0xe5, 0xe4, 0x66, 0x59, 0xec, 0x2d, 0xe7, 0x6c, 0xf6, 0xa6, 0x50, 0xa7, 0x53, 0x8a, 0x49, 0x87,
	0xcc, 0x6b, 0x07, 0xe9, 0x41, 0xcc, 0x82, 0xce, 0x2f, 0x58, 0xf2, 0xa4, 0x55, 0x87, 0x2d, 0x3f,
	0x61, 0x87, 0xaa, 0x33, 0xa3, 0x26, 0xd2, 0xa2, 0x88, 0xe6, 0xee, 0x6b, 0xc2, 0x66, 0xcf, 0xb6,
	0x06, 0xfe, 0xc0, 0xe6, 0x1b, 0x8d, 0x24, 0x4f, 0x45, 0x6c, 0x27, 0xf6, 0xed, 0xc4, 0x3a, 0xb4,
	0xcb, 0x56, 0x82, 0xae, 0x8c, 0xdd, 0xf2, 0xe3, 0xcf, 0x9f, 0xdf, 0xef, 0x29, 0xe3, 0x0b, 0x39,
	0xde, 0xd2, 0xf9, 0x7c, 0xcd, 0x96, 0x1b, 0x8d, 0xbb, 0x75, 0xff, 0x40, 0xe2, 0x54, 0xce, 0x09,
	0xb2, 0xe2, 0x2c, 0x40, 0x5a, 0xca, 0x1e, 0xaf, 0x5f, 0xaf, 0x1a, 0x83, 0xed, 0xb6, 0x14, 0x15,
	0xf4, 0x12, 0xd5, 0xbb, 0xea, 0x95, 0x6c, 0xbc, 0xab, 0x64, 0x05, 0x16, 0xbd, 0xaa, 0x70, 0xa0,
	0x7d, 0x65, 0x42, 0xe8, 0xfb, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc2, 0xd0, 0x05, 0xe2, 0x82,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// InfoClient is the client API for Info service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InfoClient interface {
	// Get an information about the service
	GetInfo(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Report, error)
	// Get a health information for the service
	GetHealth(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Health, error)
}

type infoClient struct {
	cc grpc.ClientConnInterface
}

func NewInfoClient(cc grpc.ClientConnInterface) InfoClient {
	return &infoClient{cc}
}

func (c *infoClient) GetInfo(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Report, error) {
	out := new(Report)
	err := c.cc.Invoke(ctx, "/info.Info/GetInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *infoClient) GetHealth(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Health, error) {
	out := new(Health)
	err := c.cc.Invoke(ctx, "/info.Info/GetHealth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InfoServer is the server API for Info service.
type InfoServer interface {
	// Get an information about the service
	GetInfo(context.Context, *empty.Empty) (*Report, error)
	// Get a health information for the service
	GetHealth(context.Context, *empty.Empty) (*Health, error)
}

// UnimplementedInfoServer can be embedded to have forward compatible implementations.
type UnimplementedInfoServer struct {
}

func (*UnimplementedInfoServer) GetInfo(ctx context.Context, req *empty.Empty) (*Report, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInfo not implemented")
}
func (*UnimplementedInfoServer) GetHealth(ctx context.Context, req *empty.Empty) (*Health, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHealth not implemented")
}

func RegisterInfoServer(s *grpc.Server, srv InfoServer) {
	s.RegisterService(&_Info_serviceDesc, srv)
}

func _Info_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfoServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/info.Info/GetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfoServer).GetInfo(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Info_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfoServer).GetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/info.Info/GetHealth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfoServer).GetHealth(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Info_serviceDesc = grpc.ServiceDesc{
	ServiceName: "info.Info",
	HandlerType: (*InfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _Info_GetInfo_Handler,
		},
		{
			MethodName: "GetHealth",
			Handler:    _Info_GetHealth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "info/info.proto",
}
