apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "name" . }}-config
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.service.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
data:
  default.conf: |-
    {
      "client": {
        "scheme": "{{ .Values.service.client.scheme }}",
        "host": "{{ .Values.service.client.host }}",
        "sockets": [
          {{- range $i, $value := .Values.service.client.sockets }}
          {{- if gt $i 0 }},{{- end }}
          "{{ $value }}"
          {{- end }}
        ],
        "balancer": "{{ .Values.service.client.balancer }}",
        "insecure": {{ .Values.service.client.insecure }},
        "envoyProxy": {{ .Values.service.client.envoyProxy }},
        "waitForReady": {{ .Values.service.client.waitForReady }},
        "timeout": {{ .Values.service.client.timeout }},
        "keepalive": {
          "time": {{ .Values.service.client.keepalive.time }},
          "timeout": {{ .Values.service.client.keepalive.timeout }},
          "force": {{ .Values.service.client.keepalive.force }}
        },
        "retry": {
          "active": {{ .Values.service.client.retry.active }},
          "envoy": {
            "reason": {
              "primary": "{{ .Values.service.client.retry.envoy.reason.primary }}",
              "grpc": "{{ .Values.service.client.retry.envoy.reason.grpc }}"
            },
            "count": {{ .Values.service.client.retry.envoy.count }},
            "timeout": {{ .Values.service.client.retry.envoy.timeout }}
          },
          "backoff": {
            "multiplier": {{ .Values.service.client.retry.backoff.multiplier }},
            "jitter": {{ .Values.service.client.retry.backoff.jitter }},
            "delay": {
              "min": {{ .Values.service.client.retry.backoff.delay.min }},
              "max": {{ .Values.service.client.retry.backoff.delay.max }}
            }
          }
        }
      },
      "server": {
        "port": {{ .Values.service.grpc.port }},
        "connection": {
          "idle": {{ .Values.service.connection.idle }},
          "age": {{ .Values.service.connection.age }},
          "grace": {{ .Values.service.connection.grace }},
          "keepalive": {
            "time": {{ .Values.service.connection.keepalive.time }},
            "timeout": {{ .Values.service.connection.keepalive.timeout }}
          }
        }
      },
      "info": {
        "port": {{ .Values.service.info.port }},
        "statistics": {{ .Values.service.info.statistics }}
      },
      "system": {
          "grace": {
              "period": {{ .Values.gracePeriod }}
          }
      },
      "logger": {
        "format": "{{ .Values.service.logger.format }}",
        "level": {{ .Values.service.logger.level }},
        "time": {{ printf "%t" .Values.service.logger.time }}
      }
    }
