apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "name" . }}-config
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.service.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
data:
  default.conf: |-
    {
      "server": {
        "port": {{ .Values.service.grpc.port }}
      },
      "info": {
        "port": {{ .Values.service.info.port }},
        "statistics": {{ .Values.service.info.statistics }}
      },
      "logger": {
        "format": "{{ .Values.service.logger.format }}",
        "level": {{ .Values.service.logger.level }},
        "time": {{ printf "%t" .Values.service.logger.time }}
      }
    }
