apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.service.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  {{- if .Values.service.annotations }}
  annotations:
  {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
spec:
  ports:
  {{- if .Values.service.grpc.port }}
  - port: {{ .Values.service.grpc.port }}
    targetPort: {{ .Values.service.grpc.port }}
    protocol: TCP
    name: http2
  {{- end }}
  - port: {{ .Values.service.info.port }}
    targetPort: {{ .Values.service.info.port }}
    protocol: TCP
    name: info
  selector:
    app: {{ .Values.service.name }}-{{ .Release.Namespace }}
  type: "{{ .Values.service.type }}"
  clusterIP: None
